- name: Comando help de isql
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Isql help
      ansible.builtin.command: /usr/bin/isql --help
      register: isql_help

    - name: Mostrar resultado del comando isql help
      ansible.builtin.debug:
        msg: "{{ isql_help.stdout }}"
