---
- name: Obtener y mostrar la clave privada SSH desde una credencial en Ansible Automation Platform
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Obtener la credencial de la clave privada SSH
      ansible.builtin.awx_credential:
        name: "Nombre_de_tu_credencial"
      register: credential_info

    - name: Desencriptar y mostrar la clave privada SSH
      ansible.builtin.debug:
        msg: "La clave privada SSH es {{ credential_info.inputs.ssh_key_data }}"

  vars:
    Nombre_de_tu_credencial: "satowerie"
