---
- name: Mostrar la clave privada SSH desencriptada
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Debugging encrypted SSH private key
      debug:
        var: credential_name.inputs.ssh_key_data

  vars:
    credential_name: "{{ lookup('tower_credential', 'satowerie') }}"